name: Publish

on:
  push:
    branches: master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: CI=false npm run deploy