name: Publish

on:
  push:
    branches: master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies
        run: npm install
      - name: configure git
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "<>"
          git remote set-url origin https://$DEPLOY_TOKEN@github.com/burke1791/burke-blog.git
          git remote -v
      - name: publish
        run: CI=false npm run deploy

env:
  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}